version: '3'
services:
    web:
        build: .
        ports:
            - "8080:8080"
        environment:
            - PORT=8080
            - PGHOST=db
            - PGPORT=5432
            - PGUSER=dev_user
            - PGPASSWORD=dev_pass
            - PGDATABASE=motivate_me
            - JWT_SECRET=abc123
        depends_on: 
            - db
    db:
        image: postgres:latest
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=dev_user
            - POSTGRES_PASSWORD=dev_pass
            - POSTGRES_DB=motivate_me
        volumes: 
            - ./server/db:/db
